/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1a1a1a",
        "on-secondary-fixed": "#D4AF37",
        "on-surface-variant": "#A0A0A0",
        "surface-container-lowest": "#000000",
        "secondary-container": "#2a2a2a",
        "on-secondary-container": "#D4AF37",
        "surface-container-high": "#242424",
        "on-tertiary-container": "#3fd298",
        "on-primary-fixed": "#000000",
        "on-error-container": "#ffdad6",
        "surface-dim": "#121212",
        "on-error": "#ffffff",
        "inverse-on-surface": "#000000",
        "background": "#000000",
        "on-primary-container": "#D4AF37",
        "on-primary-fixed-variant": "#B8860B",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#6ffbbe",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#2a2a2a",
        "outline-variant": "#3a3a3a",
        "inverse-surface": "#F5F5F5",
        "primary-fixed": "#D4AF37",
        "tertiary": "#003c27",
        "on-secondary": "#000000",
        "primary": "#D4AF37",
        "on-background": "#FFFFFF",
        "error": "#ba1a1a",
        "surface-container": "#1e1e1e",
        "tertiary-container": "#005639",
        "secondary": "#2a2a2a",
        "inverse-primary": "#000000",
        "on-tertiary": "#ffffff",
        "primary-container": "#B8860B",
        "surface-tint": "#D4AF37",
        "surface-bright": "#1a1a1a",
        "on-secondary-fixed-variant": "#D4AF37",
        "surface": "#121212",
        "on-primary": "#000000",
        "primary-fixed-dim": "#B8860B",
        "on-tertiary-fixed": "#002113",
        "secondary-fixed": "#D4AF37",
        "surface-container-highest": "#333333",
        "outline": "#4a4a4a",
        "surface-variant": "#1e1e1e",
        "on-surface": "#FFFFFF"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
